name: ci
on:
  push:
    tags: [ "v*" ]
    branches: [ main ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          stable: true
          go-version: '1.25'
      - uses: actions/checkout@v2
      - name: run go mod
        run: go mod tidy && go build -o basi ./cmd/
